service: spotify-downloader-nodejs
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1

functions:
  hello:
    handler: dist/handler.hello
    events:
      - http: ANY /{proxy+}
      - http: ANY /

package:
  exclude:
    - "*.ts"
    - "src/**"
    - "package*"
    - "tsconfig.json"
    - "node_modules/**/@types/**" # Exclude TypeScript type definitions
    - "node_modules/.bin/**"